### ISSUE TITLE
multiple files adding enhancement

### ISSUE THREAD

**Issue by jiewangjs** [Kenji-M-iyamoto/atom-markdown-file-linker#1]
Great package. 
But adding proper multiple files d&d support is even better.
Right now, it seems multiple insertions at once is operatable, but result is not ok.

**Comment by Kenji-M-iyamoto** [comment]
@jiewangjs, thanks a lot for contact!
Just now I modified below points when multiple files are dropped:
- change nested <a> tag to unnested and change line
   before: 
   `<a href="file1"><a href="file2"></a></a>`
   after: 
   ```
  <a href="file1"></a>
  <a href="file2"></a> 
   ```
- add pop-up message when file already existed (yes/no/cancel all)

Please try new version and I hope it fulfill your request.
if you're okay I'd like to close this issue.
